import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header, Menu } from "@/components";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} grid grid-rows-[100px_1fr] min-h-screen`}
      >
        <Header />
        { children }
      </body>
    </html>
  );
}
